### ISSUE TITLE
Compatibility with Philips Hue Entertainment API

### ISSUE THREAD

**Issue by thoukydides** [AlCalzone/node-dtls-client#6]
I am using this library with the [Philips Hue Entertainment API](https://developers.meethue.com/documentation/hue-entertainment-api) but have found that I need to disable some of the cipher suites for the initial handshake to complete successfully. 

The [attached Wireshark capture](https://github.com/AlCalzone/node-dtls-client/files/1692898/Hue-DTLS-Handshakes.zip) shows examples of both working and failing handshakes. The PSK for both exchanges is `60E98DA8E03F9939B4A347849B0AC2F0`. [node-dtls-client](https://github.com/AlCalzone/node-dtls-client) is running on `192.168.0.17`, and the Philips Hue bridge is `192.168.0.39`.

The first handshake (frames 1-8) completes successfully with `CipherSuites_1.CipherSuites.TLS_PSK_WITH_AES_256_GCM_SHA384` and `CipherSuites_1.CipherSuites.TLS_PSK_WITH_AES_256_CCM` both removed from `hello.cipher_suites` in `HandshakeHandler.js`:

Frame | Flight | Direction | Summary
----: | -----: | :-------: | :-------
 1 |  1 | client → server | Client Hello
 2 |  2 | server → client | Hello Verify Request
 3 |  3 | client → server | Client Hello
 4 |  4 | server → client | Server Hello
 5 |  4 | server → client | Server Hello Done
 6 |  5 | client → server | Client Key Exchange, Change Cipher Spec, **Finished**
 7 |  6 | server → client | Change Cipher Spec
 8 |  6 | server → client | Finished
 
The second handshake (frames 11-17) uses [node-dtls-client](https://github.com/AlCalzone/node-dtls-client) unmodified but fails with a `Bad Record MAC` alert:

Frame | Flight | Direction | Summary
----: | -----: | :-------: | :-------
11 | 1 | client → server | Client Hello
12 | 2 | server → client | Hello Verify Request
13 | 3 | client → server | Client Hello
14 | 4 | server → client | Server Hello
15 | 4 | server → client | Server Hello Done
16 | 5 | client → server | Client Key Exchange, Change Cipher Spec, <br>**Encrypted Handshake Message**
17 | 6 | server → client | **Alert (Level: Fatal, Description: Bad Record MAC)**

It appears that [node-dtls-client](https://github.com/AlCalzone/node-dtls-client) is not correctly building the Finished message (flight 5 of the handshake) with some cipher suites. Comparing the failing case (using `TLS_PSK_WITH_AES_256_GCM_SHA384`) to the working case (where `TLS_PSK_WITH_AES_256_CBC_SHA384` has been selected):
```diff
-Frame 16: 184 bytes on wire (1472 bits), 184 bytes captured (1472 bits) on interface 0
+Frame 6: 232 bytes on wire (1856 bits), 232 bytes captured (1856 bits) on interface 0
 Ethernet II, Src: AsustekC_4e:ac:33 (10:c3:7b:4e:ac:33), Dst: PhilipsL_26:a7:b5 (00:17:88:26:a7:b5)
 Internet Protocol Version 4, Src: i7pc.local.thouky.co.uk (192.168.0.17), Dst: huehub.local.thouky.co.uk (192.168.0.39)
-User Datagram Protocol, Src Port: 34123, Dst Port: 2100
+User Datagram Protocol, Src Port: 54681, Dst Port: 2100
 Datagram Transport Layer Security
     DTLSv1.2 Record Layer: Handshake Protocol: Client Key Exchange
         Content Type: Handshake (22)
         Version: DTLS 1.2 (0xfefd)
         Epoch: 0
         Sequence Number: 2
         Length: 54
         Handshake Protocol: Client Key Exchange
             Handshake Type: Client Key Exchange (16)
             Length: 42
             Message Sequence: 2
             Fragment Offset: 0
             Fragment Length: 42
             PSK Client Params
                 Identity Length: 40
                 Identity: 39536657376959777a3439654970617071374553696d6739...
     DTLSv1.2 Record Layer: Change Cipher Spec Protocol: Change Cipher Spec
         Content Type: Change Cipher Spec (20)
         Version: DTLS 1.2 (0xfefd)
         Epoch: 0
         Sequence Number: 3
         Length: 1
         Change Cipher Spec Message
-    Record Layer
+    DTLSv1.2 Record Layer: Handshake Protocol: Finished
         Content Type: Handshake (22)
         Version: DTLS 1.2 (0xfefd)
         Epoch: 1
         Sequence Number: 0
-        Length: 48
-        Handshake Protocol
+        Length: 96
+        Handshake Protocol: Finished
+            Handshake Type: Finished (20)
+            Length: 12
+            Message Sequence: 3
+            Fragment Offset: 0
+            Fragment Length: 12
+            Verify Data
```

Are these cipher suites handled correctly by [node-dtls-client](https://github.com/AlCalzone/node-dtls-client)?

Is there a clean way for a user of this library to disable some of the cipher suites?
 (Philips Hue officially only supports `TLS_PSK_WITH_AES_128_GCM_SHA256`, so having a way to force its use without modifying the library source code would be good.)

**Comment by AlCalzone** [comment]
Thanks for the extended report. I'll look into it - no guarantees as to when I'll have the time.
I tried to implement those cipher suites as best as I could without testing since my only device to test against is an IKEA tradfri gateway, which only supports `TLS_PSK_WITH_AES_128_CCM_8` or `TLS_PSK_WITH_AES_128_CBC_SHA256`. So it's entirely possible I made a mistake in the definitions somewhere. The CCM and GCM encryption was taken from well-tested libraries, so they should be fine.

> Is there a clean way for a user of this library to disable some of the cipher suites?

Not yet, I'll add one.

**Comment by thoukydides** [comment]
Please let me know if there is anything that you would like me to test, or if you need any additional information.

**Comment by AlCalzone** [comment]
Apparently, I switched the key and block sizes for CCM and GCM ciphers. This is no problem when both are 128 bit, so I didn't notice it.
Should be fixed in dba81be, please test again.

**Comment by AlCalzone** [comment]
Selection of cipher suites should be possible with https://github.com/AlCalzone/node-dtls-client/tree/specify-ciphersuites (untested).
The `DtlsOptions` object you pass to the has a new optional parameter `ciphers` which is an array of cipher suites, e.g.
```js
[
    "TLS_PSK_WITH_3DES_EDE_CBC_SHA",
    "TLS_PSK_WITH_AES_128_CBC_SHA",
    "TLS_PSK_WITH_AES_256_CBC_SHA"
]
```

**Comment by thoukydides** [comment]
Both the non-128-bit key size fix and the selection of cipher suites appear to work correctly. Thank you for the quick fix and new feature.

All of the AES cipher suites now work correctly with the Philips Hue bridge:
 * `TLS_PSK_WITH_AES_128_CBC_SHA`
 * `TLS_PSK_WITH_AES_256_CBC_SHA`
 * `TLS_PSK_WITH_AES_128_CBC_SHA256`
 * `TLS_PSK_WITH_AES_256_CBC_SHA384`
 * `TLS_PSK_WITH_AES_128_GCM_SHA256`
 * `TLS_PSK_WITH_AES_256_GCM_SHA384`
 * `TLS_PSK_WITH_AES_128_CCM`
 * `TLS_PSK_WITH_AES_256_CCM`
 * `TLS_PSK_WITH_AES_128_CCM_8`
 * `TLS_PSK_WITH_AES_256_CCM_8`

However, there may be a problem with the implementation of `TLS_PSK_WITH_3DES_EDE_CBC_SHA`. Forcing use of this cipher results in the following error:
```
Error: Invalid IV length
    at new Cipheriv (crypto.js:219:16)
    at Object.Cipheriv (crypto.js:217:12)
    at CipherSuite.ret [as _cipher] (/home/alex/Documents/Hue/hueentertain/node_modules/node-dtls-client/build/TLS/BlockCipher.js:36:29)
    at ConnectionState.ret [as _cipher] (/home/alex/Documents/Hue/hueentertain/node_modules/node-dtls-client/build/TLS/CipherSuite.js:112:56)
    at RecordLayer.processOutgoingMessage (/home/alex/Documents/Hue/hueentertain/node_modules/node-dtls-client/build/DTLS/RecordLayer.js:52:44)
    at /home/alex/Documents/Hue/hueentertain/node_modules/node-dtls-client/build/DTLS/RecordLayer.js:68:76
    at Array.map (<anonymous>)
    at RecordLayer.sendFlight (/home/alex/Documents/Hue/hueentertain/node_modules/node-dtls-client/build/DTLS/RecordLayer.js:68:42)
    at ClientHandshakeHandler.sendFlight_finish (/home/alex/Documents/Hue/hueentertain/node_modules/node-dtls-client/build/DTLS/HandshakeHandler.js:326:26)
    at Object.ClientHandshakeHandler.handle._a.(anonymous function) (/home/alex/Documents/Hue/hueentertain/node_modules/node-dtls-client/build/DTLS/HandshakeHandler.js:100:35)
```

Here is a [Wireshark capture](https://github.com/AlCalzone/node-dtls-client/files/1694671/TLS_PSK_WITH_3DES_EDE_CBC_SHA.zip) for the handshake. It looks like the error occurs while node-dtls-client is processing flight 4 from the server.

**Comment by AlCalzone** [comment]
Brilliant! 
3DES uses 8-byte block and IV sizes, not 16. => should be fixed in 5a8a4e0

**Comment by thoukydides** [comment]
`TLS_PSK_WITH_3DES_EDE_CBC_SHA` also works with the latest version. Perfect!

Thank you.

**Comment by AlCalzone** [comment]
Thank you for testing! I'll close this. If any problems arise, feel free to reopen or make a new issue.

**Comment by AlCalzone** [comment]
aaaaand published as 0.3.0

**Comment by hayes** [comment]
@thoukydides any chance you would be willing to share a bit of the code you are using for opening the dtls socket for the hue entertainment api?  I have also been trying to get this to work and am running into bad_record_mac errors.

The config I am using to try to connect looks something like:
```javascript
const options = {
  type: "udp4",
  address: this.bridge.ipaddress,
  port: 2100,
  psk: { [this.username]: Buffer.from(this.clientKey, 'hex').toString('ascii') },
  timeout: 1000, // in ms, optional, minimum 100, default 1000
  ciphers: ['TLS_PSK_WITH_AES_128_GCM_SHA256']
}
```

**Comment by thoukydides** [comment]
@hayes, I am using code like this:
```JS
let request = require('request');
let dtls = require('node-dtls-client').dtls

const hue_hub       = 'huehub.local.thouky.co.uk';
const hue_clientkey = new Buffer('0123456789ABCDEF0123456789ABCDEF', 'hex');
const hue_username  = 'abcdefghijklmnopqrstuvwxyzabcdefghijklmn';

let options = {
    method: 'PUT',
    url:    'http://' + hue_hub + '/api/' + hue_username + '/groups/46',
    json:   true,
    body: {
        "stream": {
            "active": true
        }
    }
};
request(options, (err, response, body) => {
    if (response && response.statusCode < 400) {
        let options = {
            type:    'udp4',
            address: hue_hub,
            port:    2100,
            psk:     {},
            timeout: 1000
        };
        options.psk[hue_username] = hue_clientkey;
        let socket = dtls
            .createSocket(options)
            .on('connected', () => {
                // Start streaming
            })
    }
});
```
When the correct `psk` is used I do not see any `bad_record_mac` errors.

**Comment by hayes** [comment]
thanks! That looks pretty much like what I have been doing.  Must have something wrong with my credentials.  But having confirmation that this should work and isn't an issue with the client or the options I am passing is really helpful.

thanks for sharing!

**Comment by thoukydides** [comment]
@hayes, I suspect that your use of `.toString('ascii')` on the client key is the problem. The Hue client keys are not representable in ASCII. Just pass the `Buffer` to node-dtls-client.

**Comment by hayes** [comment]
@thoukydides it looks like the app I was using got blacklisted.  I had tried re fetching the key to make sure it was right, which didn't work, but creating a new app with a new username/psk did the trick.  

Before you found this issue, I had started building out my own dtls client and sent a LOT of malformed messages while trying to get the handshake right, maybe that caused it to get blacklisted?

Anyways, just changed my first light using the new api, thanks for your help!

**Comment by Fabiantjoeaon** [comment]
@hayes @thoukydides 
Hi guys, I'm also trying to get my Hue working with dlts, but I'm a total noob on UDP and DLTS however, I was wondering if you could give me any insights on how to send a message to a light in a Buffer? I got my connection working.


```

        dtls.createSocket(options)
            .on("connected", e => {
                // I have truly no idea.. :')
                const msg = new Buffer("Hue");
                msg[1] = ["H", "u", "e", "S", "t", "r", "e", "a", "m"];
                console.log("CONNECTED", e);
            })
            .on("error", e => {
                console.log("ERROR", e);
            })
            .on("message", msg => {
                console.log("MESSAGE", msg);
            })
            .on("close", e => {
                console.log("CLOSE", e);
            });
```

Thanks in advance!

**Comment by AlCalzone** [comment]
@Fabiantjoeaon you want to store the return value of `dtls.createSocket` in a variable and use that to send the buffer, e.g. like this:
```js
        const socket = dtls.createSocket(options)
            .on("connected", e => {
                console.log("CONNECTED", e);
                const msg = new Buffer("message payload");
                socket.send(msg);
            })
            .on("error", e => {
                console.log("ERROR", e);
            })
            .on("message", msg => {
                console.log("MESSAGE", msg);
            })
            .on("close", e => {
                console.log("CLOSE", e);
            });
```
The contents of that message buffer depend on the higher-level protocol used.

**Comment by hayes** [comment]
The contents of the buffer you want to send is described here: https://developers.meethue.com/documentation/hue-entertainment-api

(You need to sign up for the r a free hue Dev account) 

For most cases you'll want to set up some kind of loop that sends the colors for all your lights at a fairly high frequency (20ms?) 

If you need a working example, I can try to throw something together that has all of the settup and initializing the streaming API

**Comment by Fabiantjoeaon** [comment]
@AlCalzone 
Should have posted more of my code, that's what I've already been doing:
```
        const socket = dtls.createSocket(options);
        socket
            .on("connected", e => {
                const msg = new Buffer();

                // msg[1] = ["H", "u", "e", "S", "t", "r", "e", "a", "m"];
                console.log("CONNECTED", e);
                socket.send(msg, e => {
                    console.log("SEND", e);
                });
            })
```

Thanks for the insight anyway!

**Comment by Fabiantjoeaon** [comment]
@hayes 
I see. I already have a developer account on Philips Hue (I already got a setup working through HTTP protocol, but for my app, it wasn't responsive enough yet, so I'm trying Entertainment API with UDP). I've read the docs multiple times, but haven't found a working implementation yet.

My question is more; I really have no clue how to format the message I send with a buffer ( and do you use setTimeout to send at a high frequency rate? ), I've never used Streams and Buffers, and binaries. This, is for example what I've been trying out yesterday:

```
                msg[0] = [
                    "H",
                    "u",
                    "e",
                    "S",
                    "t",
                    "r",
                    "e",
                    "a",
                    "m"
                ]);
                msg[1] = new Buffer(0x01, 0x00);
                msg[2] = new Buffer(0x00, 0x00);
                msg[3] = new Buffer(0x00);
                msg[4] = new Buffer(14, "hex");
                msg[5] = new Buffer(0xff, 0xff, 0x00, 0x00, 0x00, 0x00);
                // msg[0] = new ArrayBuffer()
                // msg[1] = ["H", "u", "e", "S", "t", "r", "e", "a", "m"];
                console.log("CONNECTED", e);
                socket.send(msg, e => {
                    console.log("SEND", e);
                });
```

I don't think I'll figure it out by myself, so a working example would be of so much help, if you're willing to take the time :)!

**Comment by AlCalzone** [comment]
I think you misunderstand how Buffers work in NodeJS: https://nodejs.org/api/buffer.html
Each index of the buffer represents a single byte, not entire arrays or other buffers.

I think what you are trying to do should look similar to this:
```ts
const msg = Buffer.concat([
    Buffer.from("Huestream", "ascii"),
    Buffer.from([
        0x01, 0x00, 
        0x00, 0x00, 
        0x00, 
        0x14 /* or decimal 14? */, 
        0xff, 0xff, 0x00, 0x00, 0x00, 0x00
    ])
]);
```

**Comment by Fabiantjoeaon** [comment]
@AlCalzone 

Ahh I see.
Yes, as I previously mentioned, I have no clue on how to communicate with my Philips Hue setup with Buffers, because I simply don't understand how they work (never worked with Bytes etc.), I did do some research on it, but as the server expects a very specific format, which is very complex for me. I'd thought I might best have a look into someone's code who has already been communicating with the Philips Hue Entertainment API.

I'll try it out again however with the information you just send me.

**Comment by nickysemenza** [comment]
@Fabiantjoeaon were you able to get this to work?

**Comment by Fabiantjoeaon** [comment]
@nickysemenza Hey, yeah I managed to get it working, what's exactly not working for you?

Using `axios`, this is the call I make to my hue system (don't mind the values I grab from local state and my color helper methods (like `rgbToXY`)

`axios
    .put(
        `http://${constants.HUE_HOST}/api/${
            constants.STREAMING_USERNAME
        }/groups/${constants.STREAMING_GROUP}`,
        {
            stream: {
                active: true
            }
        }
    )
    .then(res => {
        console.log(res.data);
        const options = {
            type: "udp4",
            address: constants.HUE_HOST,
            port: 2100,
            psk: {},
            timeout: 1000 // in ms, optional, minimum 100, default 1000
            // ciphers: ["TLS_PSK_WITH_AES_128_GCM_SHA256"]
        };
        options.psk[constants.STREAMING_USERNAME] = new Buffer(
            constants.STREAMING_CLIENT_KEY,
            "hex"
        );

        const socket = dtls.createSocket(options);
        socket
            .on("connected", e => {
                //http://cactus.io/resources/toolbox/decimal-binary-octal-hexadecimal-conversion
                setInterval(() => {
                    const {
                        color: { r: r1, g: g1, b: b1 },
                        brightness: brightness1
                    } = store.state.light_1;
                    const {
                        color: { r: r2, g: g2, b: b2 },
                        brightness: brightness2
                    } = store.state.light_2;

                    const { x: x1, y: y1 } = rgbToXY(r1, g1, b1);
                    const { x: x2, y: y2 } = rgbToXY(r2, g2, b2);

                    const message = Buffer.concat([
                        Buffer.from("HueStream", "ascii"),
                        // prettier-ignore
                        Buffer.from([
                            0x01, 0x00, //version 1.0
                            0x07, //sequence number 7
                            0x00, 0x00, //Reserved write 0’s
                            0x01, //color mode XY
                            0x00, // Reserved, write 0’s

                            0x00, 0x00, store.state.light_1.id, // LIGHT 14
                            // X            // Y            // BRIGHTNESS
                            x1.xOne, x1.xTwo, y1.yOne, y1.yTwo, brightness1, brightness1,

                            0x00, 0x00, store.state.light_2.id, // LIGHT 15
                            // X            // Y            // BRIGHTNESS
                            x2.xOne, x2.xTwo, y2.yOne, y2.yTwo, brightness2, brightness2,
                        ])
                    ]);
                    socket.send(message, e => {});
                }, 30);
            })
            .on("error", e => {
                console.log("ERROR", e);
            })
            .on("close", e => {
                console.log("CLOSE", e);
            });
    })
    .catch(console.log);`

**Comment by AlCalzone** [comment]
> Anything obvious I could be missing?

https://github.com/Fabiantjoeaon/ableton-hue-project/blob/master/src/index.js#L67

Here, it starts with a sequence number of 7 in the message, which seems to take the handshake into account. Your code starts with 1, probably causing the message to be ignored.

**Comment by nickysemenza** [comment]
Hm I changed it to 7, and still nothing :/ 
I don't think that is it though, the [hue API says](https://developers.meethue.com/documentation/hue-entertainment-api) "Can be used to indicate the message sequence number. Currently it is ignored by the bridge. " 

In terms of the protocol, UDP doesn't guarantee packet delivery, and furthermore, packets can arrive in any order. adding a sequence number at the application layer is a common practice - the server can keep track of the most recently received sequence number, and discard incoming packets that are _lower_ than that sequence number - as they would be 'late', and, since this is realtime/streaming, they are useless out of order / late. I'm guessing that they will add something like this to the Hue bridge in the future? 

Typically the practice is for clients to keep track of the sequence number, and increase it every time they send a message.

Looks like your repo is missing some files like `./helpers/rgbToXY` so I can't try running it locally.

**Comment by AlCalzone** [comment]
> Can be used to indicate the message sequence number. Currently it is ignored by the bridge

Okay, good to know. The underlying DTLS protocol enforces the sequence number as it is part of the encryption and verification, but that is handled internally.

**Comment by gidhin** [comment]
Hi
I am facing the problem in DTLS commissioning
Here i add my Error:

Error: ./node_modules/node-dtls-client/build/dtls.js
Module not found: Error: Can't resolve 'dgram' in '/Users/vetri/Vetri's Work Space/Projects/BLE_Stack/BLE/node_modules/node-dtls-client/build'

My code : 

let request = require('request');
let dtls = require('node-dtls-client').dtls

 let options = {
      type:    'udp4',
      address: '10.42.0.1',
      port:    49191,
      psk:     {},
      timeout: 1000
  };
    const socket = dtls.createSocket(option).on("connected", () => {/* start sending data */
      console.log("dtls testing");
    });
  }

Thanks in advance

**Comment by AlCalzone** [comment]
Are you executing your code with nodejs?

**Comment by gidhin** [comment]
yes, i'm doing on ionic 3 application. i have install "node-dtls-client"
from npm.

Thanks and Regards,
Gidhin S

**Comment by AlCalzone** [comment]
`dgram` is a native NodeJS module, which is required by `node-dtls-client`, like I posted in response to your other question: https://github.com/AlCalzone/node-dtls-client/issues/16#issuecomment-489994248

I'm not familiar with ionic, but I guess you need some kind of polyfill or replacement to use `dgram` there.
Unfortunately, I cannot help you with that. If you find a replacement module, let me know, so I can look into a way to configure `node-dtls-client` to use that module instead. But please open a separate issue for that.

**Comment by gidhin** [comment]
Thank you @AlCalzone . 

I have fixed that issue, i found new issue.


error:
ScanWifiPage.html:26 ERROR TypeError: dtls.createSocket is not a function
    at ScanWifiPage.webpackJsonp.251.ScanWifiPage.openThread (main.js:1332)
    at Object.eval [as handleEvent] (ScanWifiPage.html:26)
    at handleEvent (vendor.js:14275)
    at callWithDebugContext (vendor.js:15784)
    at Object.debugHandleEvent [as handleEvent] (vendor.js:15371)
    at dispatchEvent (vendor.js:10690)
    at vendor.js:11315
    at HTMLElement.<anonymous> (vendor.js:53326)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:5437)
View_ScanWifiPage_1 @ ScanWifiPage.html:26
DebugContext_.logError @ vendor.js:15724
ErrorHandler.handleError @ vendor.js:2196
IonicErrorHandler.handleError @ vendor.js:236987
dispatchEvent @ vendor.js:10694
(anonymous) @ vendor.js:11315
(anonymous) @ vendor.js:53326
t.invokeTask @ polyfills.js:3
onInvokeTask @ vendor.js:5437
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2


my Code : 
let request = require('request');
    const dtls = require('is-dtls');

let options = {
      type: 'udp4',
      address: '10.42.0.1',
      port: 49191,
      psk: {},
      timeout: 1000
    };
    const socket = dtls.createSocket(option);
    socket.on("connected", () => {/* start sending data */
      console.log("dtls testing");
    });
  }

using this plugin with version no: "@nodertc/dtls": "^0.6.0",

**Comment by AlCalzone** [comment]
@gidhin You are using a different module now, that has nothing to do with this one.

**Comment by gidhin** [comment]
Thank you. Is there any other option for using DTLS client in javascript.

**Comment by AlCalzone** [comment]
None that I know of

**Comment by gidhin** [comment]
@AlCalzone Thank you so much. it will work on native Android code right ?

**Comment by AlCalzone** [comment]
I'm not sure. Isn't Android written in Java?

**Comment by gidhin** [comment]
Android written in Java only. I thing it is possible in Android. what
language used to written in "node-dtls-client"
 plugin?  C++ ?
Thanks and Regards,
Gidhin S

**Comment by AlCalzone** [comment]
If you take a look at the repo you'll see its TypeScript / JS

**Comment by gidhin** [comment]
@AlCalzone If it JS/TypeScript it should work for me also. Im developed my application in TypeScript.

**Comment by gidhin** [comment]
@AlCalzone 
Hi 
Im getting this error  :
The DTLS handshake timed out
    at Socket.expectHandshake

This is my code


var dtls = require("node-dtls-client").dtls;
options = {
    type: "udp6",
    address: "10.42.0.1",
    port: 49888,
    psk: {
        "psk_hint": "PSK"
    },
    timeout: 1000, // in ms, optional, minimum 100, default 1000
    ciphers: ["TLS_PSK_WITH_3DES_EDE_CBC_SHA",
        "TLS_PSK_WITH_AES_128_CBC_SHA",
        "TLS_PSK_WITH_AES_256_CBC_SHA",
        "TLS_PSK_WITH_AES_128_CBC_SHA256",
        "TLS_PSK_WITH_AES_256_CBC_SHA384",
        "TLS_PSK_WITH_AES_128_GCM_SHA256",
        "TLS_PSK_WITH_AES_256_GCM_SHA384",
        "TLS_PSK_WITH_AES_128_CCM_8",
        "TLS_PSK_WITH_AES_256_CCM_8",
    ] // optional array of (D)TLS cipher suites, e.g. ["TLS_PSK_WITH_AES_128_CCM"]
}

const socket = dtls.createSocket(options, function (err, res) {
        console.log("err", err);
        console.log("res", res);
    })
    // create a socket and initialize the secure connection
    // .createSocket(options /* DtlsOptions */ )
    // subscribe events
    .on("connected", e => {
        /* start sending data */
        console.log("connected");
        console.log("CONNECTED", e);
        
    })
    .on("error", e => {
        console.log("error gid", e);
    })
    .on("message", (msg /* Buffer */ ) => {
        console.log("message", msg);
    })
    .on("close", e => {
        console.log("close", e);
    });


How can i pass message for handshaking ?

**Comment by AlCalzone** [comment]
> The DTLS handshake timed out

means that the handshake was not finished in time. This usually happens if the IP address is wrong, if gateway did not respond or if it ignored your connection attempt due to wrong credentials.

**Comment by willyboy** [comment]
> I think you misunderstand how Buffers work in NodeJS: https://nodejs.org/api/buffer.html
> Each index of the buffer represents a single byte, not entire arrays or other buffers.
> 
> I think what you are trying to do should look similar to this:
> 
> ```ts
> const msg = Buffer.concat([
>     Buffer.from("Huestream", "ascii"),
>     Buffer.from([
>         0x01, 0x00, 
>         0x00, 0x00, 
>         0x00, 
>         0x14 /* or decimal 14? */, 
>         0xff, 0xff, 0x00, 0x00, 0x00, 0x00
>     ])
> ]);
> ```
> 
> Sadly I can't provide you with an example because I'm using this as the transport layer in my CoAP library which most has completely different message formats. Sending the messages is also pretty complex there because they need to be ordered, resent on loss and rate-limited.

If anyone uses this example just note, the S should be capitalized and it does matter :D

**Comment by AlCalzone** [comment]
Updated, thanks :)
